name: Run Tests before Merge

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs: ubuntu-latest

  steps:
    - name: Check Repository
    - uses: actions/checkout@v3

    - name: Set up Node
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'

    - name: Install dependencies
    - run: yarn install --frozen-lockfile

    - name: Run Tests
    - run: yarn test

    - name: Check Test Coverage
      run: yarn test --coverage
